//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Client.Service {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ExtendedPropertiesDictionary", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="ExtendedProperties", KeyName="Name", ValueName="ExtendedProperty")]
    [System.SerializableAttribute()]
    public class ExtendedPropertiesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsAddedToCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="AddedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="AddedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsAddedToCollectionProperties : System.Collections.Generic.Dictionary<string, POS.Client.Service.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectList", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="ObjectValue")]
    [System.SerializableAttribute()]
    public class ObjectList : System.Collections.Generic.List<object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ObjectsRemovedFromCollectionProperties", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="DeletedObjectsForProperty", KeyName="CollectionPropertyName", ValueName="DeletedObjects")]
    [System.SerializableAttribute()]
    public class ObjectsRemovedFromCollectionProperties : System.Collections.Generic.Dictionary<string, POS.Client.Service.ObjectList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="OriginalValuesDictionary", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="OriginalValues", KeyName="Name", ValueName="OriginalValue")]
    [System.SerializableAttribute()]
    public class OriginalValuesDictionary : System.Collections.Generic.Dictionary<string, object> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfMenuItemKeBX3iM4", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="MenuItem")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfMenuItemKeBX3iM4 : System.Collections.Generic.List<POS.Data.Model.MenuItem> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfBillItemKeBX3iM4", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="BillItem")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfBillItemKeBX3iM4 : System.Collections.Generic.List<POS.Data.Model.BillItem> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfBillKeBX3iM4", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="Bill")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfBillKeBX3iM4 : System.Collections.Generic.List<POS.Data.Model.Bill> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfCheckKeBX3iM4", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="Check")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfCheckKeBX3iM4 : System.Collections.Generic.List<POS.Data.Model.Check> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfUserKeBX3iM4", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="User")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfUserKeBX3iM4 : System.Collections.Generic.List<POS.Data.Model.User> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfPriceKeBX3iM4", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="Price")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfPriceKeBX3iM4 : System.Collections.Generic.List<POS.Data.Model.Price> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="TrackableCollectionOfMenuGroupKeBX3iM4", Namespace="http://schemas.datacontract.org/2004/07/POS.Data.Model", ItemName="MenuGroup")]
    [System.SerializableAttribute()]
    public class TrackableCollectionOfMenuGroupKeBX3iM4 : System.Collections.Generic.List<POS.Data.Model.MenuGroup> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.Service1")]
    public interface Service1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/DivisionDel", ReplyAction="http://tempuri.org/Service1/DivisionDelResponse")]
        bool DivisionDel(POS.Data.Model.Division value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/DivisionIns", ReplyAction="http://tempuri.org/Service1/DivisionInsResponse")]
        bool DivisionIns(POS.Data.Model.Division value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/DivisionUpd", ReplyAction="http://tempuri.org/Service1/DivisionUpdResponse")]
        bool DivisionUpd(POS.Data.Model.Division value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/DivisionsGet", ReplyAction="http://tempuri.org/Service1/DivisionsGetResponse")]
        POS.Data.Model.Division[] DivisionsGet(System.Nullable<System.Guid> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/UserGroupDel", ReplyAction="http://tempuri.org/Service1/UserGroupDelResponse")]
        bool UserGroupDel(POS.Data.Model.UserGroup value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/UserGroupIns", ReplyAction="http://tempuri.org/Service1/UserGroupInsResponse")]
        bool UserGroupIns(POS.Data.Model.UserGroup value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/UserGroupUpd", ReplyAction="http://tempuri.org/Service1/UserGroupUpdResponse")]
        bool UserGroupUpd(POS.Data.Model.UserGroup value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/UserGroupGet", ReplyAction="http://tempuri.org/Service1/UserGroupGetResponse")]
        POS.Data.Model.UserGroup[] UserGroupGet(System.Nullable<System.Guid> id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/UserDel", ReplyAction="http://tempuri.org/Service1/UserDelResponse")]
        bool UserDel(POS.Data.Model.User value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/UserIns", ReplyAction="http://tempuri.org/Service1/UserInsResponse")]
        bool UserIns(POS.Data.Model.User value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/UserSel", ReplyAction="http://tempuri.org/Service1/UserSelResponse")]
        POS.Data.Model.User[] UserSel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/UserUpd", ReplyAction="http://tempuri.org/Service1/UserUpdResponse")]
        bool UserUpd(POS.Data.Model.User value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1Channel : POS.Client.Service.Service1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<POS.Client.Service.Service1>, POS.Client.Service.Service1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool DivisionDel(POS.Data.Model.Division value) {
            return base.Channel.DivisionDel(value);
        }
        
        public bool DivisionIns(POS.Data.Model.Division value) {
            return base.Channel.DivisionIns(value);
        }
        
        public bool DivisionUpd(POS.Data.Model.Division value) {
            return base.Channel.DivisionUpd(value);
        }
        
        public POS.Data.Model.Division[] DivisionsGet(System.Nullable<System.Guid> id) {
            return base.Channel.DivisionsGet(id);
        }
        
        public bool UserGroupDel(POS.Data.Model.UserGroup value) {
            return base.Channel.UserGroupDel(value);
        }
        
        public bool UserGroupIns(POS.Data.Model.UserGroup value) {
            return base.Channel.UserGroupIns(value);
        }
        
        public bool UserGroupUpd(POS.Data.Model.UserGroup value) {
            return base.Channel.UserGroupUpd(value);
        }
        
        public POS.Data.Model.UserGroup[] UserGroupGet(System.Nullable<System.Guid> id) {
            return base.Channel.UserGroupGet(id);
        }
        
        public bool UserDel(POS.Data.Model.User value) {
            return base.Channel.UserDel(value);
        }
        
        public bool UserIns(POS.Data.Model.User value) {
            return base.Channel.UserIns(value);
        }
        
        public POS.Data.Model.User[] UserSel() {
            return base.Channel.UserSel();
        }
        
        public bool UserUpd(POS.Data.Model.User value) {
            return base.Channel.UserUpd(value);
        }
    }
}
