//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS.Client.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.Service1")]
    public interface Service1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/Login", ReplyAction="http://tempuri.org/Service1/LoginResponse")]
        System.Guid Login(string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/Delete", ReplyAction="http://tempuri.org/Service1/DeleteResponse")]
        int Delete(POS.Data.Model.Tables tab, string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/Insert", ReplyAction="http://tempuri.org/Service1/InsertResponse")]
        int Insert(POS.Data.Model.Tables tab, string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/Update", ReplyAction="http://tempuri.org/Service1/UpdateResponse")]
        int Update(POS.Data.Model.Tables tab, string item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Service1/Sel_ById", ReplyAction="http://tempuri.org/Service1/Sel_ByIdResponse")]
        string Sel_ById(POS.Data.Model.Tables tab, System.Nullable<int> id, POS.Data.Model.IdColumn col);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1Channel : POS.Client.Service.Service1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<POS.Client.Service.Service1>, POS.Client.Service.Service1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Guid Login(string password) {
            return base.Channel.Login(password);
        }
        
        public int Delete(POS.Data.Model.Tables tab, string item) {
            return base.Channel.Delete(tab, item);
        }
        
        public int Insert(POS.Data.Model.Tables tab, string item) {
            return base.Channel.Insert(tab, item);
        }
        
        public int Update(POS.Data.Model.Tables tab, string item) {
            return base.Channel.Update(tab, item);
        }
        
        public string Sel_ById(POS.Data.Model.Tables tab, System.Nullable<int> id, POS.Data.Model.IdColumn col) {
            return base.Channel.Sel_ById(tab, id, col);
        }
    }
}
