//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace POS.Data.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Bill))]
    [KnownType(typeof(User))]
    [KnownType(typeof(MenuItem))]
    public partial class BillItem: INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public System.DateTime CreatedTime
        {
            get { return _createdTime; }
            set
            {
                if (_createdTime != value)
                {
                    _createdTime = value;
                    OnPropertyChanged("CreatedTime");
                }
            }
        }
        private System.DateTime _createdTime;
    
        [DataMember]
        public System.Guid CreatedByUser
        {
            get { return _createdByUser; }
            set
            {
                if (_createdByUser != value)
                {
                    _createdByUser = value;
                    OnPropertyChanged("CreatedByUser");
                }
            }
        }
        private System.Guid _createdByUser;
    
        [DataMember]
        public System.Guid BillId
        {
            get { return _billId; }
            set
            {
                if (_billId != value)
                {
                    _billId = value;
                    OnPropertyChanged("BillId");
                }
            }
        }
        private System.Guid _billId;
    
        [DataMember]
        public System.Guid MenuItemId
        {
            get { return _menuItemId; }
            set
            {
                if (_menuItemId != value)
                {
                    _menuItemId = value;
                    OnPropertyChanged("MenuItemId");
                }
            }
        }
        private System.Guid _menuItemId;
    
        [DataMember]
        public decimal Amount
        {
            get { return _amount; }
            set
            {
                if (_amount != value)
                {
                    _amount = value;
                    OnPropertyChanged("Amount");
                }
            }
        }
        private decimal _amount;
    
        [DataMember]
        public Nullable<System.DateTime> ModifiedTime
        {
            get { return _modifiedTime; }
            set
            {
                if (_modifiedTime != value)
                {
                    _modifiedTime = value;
                    OnPropertyChanged("ModifiedTime");
                }
            }
        }
        private Nullable<System.DateTime> _modifiedTime;
    
        [DataMember]
        public Nullable<System.Guid> ModifiedByUser
        {
            get { return _modifiedByUser; }
            set
            {
                if (_modifiedByUser != value)
                {
                    _modifiedByUser = value;
                    OnPropertyChanged("ModifiedByUser");
                }
            }
        }
        private Nullable<System.Guid> _modifiedByUser;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Bill Bill
        {
            get { return _bill; }
            set
            {
                if (!ReferenceEquals(_bill, value))
                {
                    _bill = value;
                    OnNavigationPropertyChanged("Bill");
                }
            }
        }
        private Bill _bill;
    
        [DataMember]
        public User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    _user = value;
                    OnNavigationPropertyChanged("User");
                }
            }
        }
        private User _user;
    
        [DataMember]
        public MenuItem MenuItem
        {
            get { return _menuItem; }
            set
            {
                if (!ReferenceEquals(_menuItem, value))
                {
                    _menuItem = value;
                    OnNavigationPropertyChanged("MenuItem");
                }
            }
        }
        private MenuItem _menuItem;
    
        [DataMember]
        public User User1
        {
            get { return _user1; }
            set
            {
                if (!ReferenceEquals(_user1, value))
                {
                    _user1 = value;
                    OnNavigationPropertyChanged("User1");
                }
            }
        }
        private User _user1;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        //protected bool IsDeserializing { get; private set; }
    
        //[OnDeserializing]
        //public void OnDeserializingMethod(StreamingContext context)
        //{
        //    IsDeserializing = true;
        //}
    
        //[OnDeserialized]
        //public void OnDeserializedMethod(StreamingContext context)
        //{
        //    IsDeserializing = false;
        //    ChangeTracker.ChangeTrackingEnabled = true;
        //}
    
        //protected virtual void ClearNavigationProperties()
        //{
        //    Bill = null;
        //    User = null;
        //    MenuItem = null;
        //    User1 = null;
        //}

        #endregion
        #region Association Fixup
    
        //private void FixupBill(Bill previousValue)
        //{
        //    if (IsDeserializing)
        //    {
        //        return;
        //    }
    
        //    if (previousValue != null && previousValue.BillItems.Contains(this))
        //    {
        //        previousValue.BillItems.Remove(this);
        //    }
    
        //    if (Bill != null)
        //    {
        //        if (!Bill.BillItems.Contains(this))
        //        {
        //            Bill.BillItems.Add(this);
        //        }
    
        //        BillId = Bill.Id;
        //    }
        //    if (ChangeTracker.ChangeTrackingEnabled)
        //    {
        //        if (ChangeTracker.OriginalValues.ContainsKey("Bill")
        //            && (ChangeTracker.OriginalValues["Bill"] == Bill))
        //        {
        //            ChangeTracker.OriginalValues.Remove("Bill");
        //        }
        //        else
        //        {
        //            ChangeTracker.RecordOriginalValue("Bill", previousValue);
        //        }
        //        if (Bill != null && !Bill.ChangeTracker.ChangeTrackingEnabled)
        //        {
        //            Bill.StartTracking();
        //        }
        //    }
        //}
    
        //private void FixupUser(User previousValue)
        //{
        //    if (IsDeserializing)
        //    {
        //        return;
        //    }
    
        //    if (previousValue != null && previousValue.BillItems.Contains(this))
        //    {
        //        previousValue.BillItems.Remove(this);
        //    }
    
        //    if (User != null)
        //    {
        //        if (!User.BillItems.Contains(this))
        //        {
        //            User.BillItems.Add(this);
        //        }
    
        //        CreatedByUser = User.Id;
        //    }
        //    if (ChangeTracker.ChangeTrackingEnabled)
        //    {
        //        if (ChangeTracker.OriginalValues.ContainsKey("User")
        //            && (ChangeTracker.OriginalValues["User"] == User))
        //        {
        //            ChangeTracker.OriginalValues.Remove("User");
        //        }
        //        else
        //        {
        //            ChangeTracker.RecordOriginalValue("User", previousValue);
        //        }
        //        if (User != null && !User.ChangeTracker.ChangeTrackingEnabled)
        //        {
        //            User.StartTracking();
        //        }
        //    }
        //}
    
        //private void FixupMenuItem(MenuItem previousValue)
        //{
        //    if (IsDeserializing)
        //    {
        //        return;
        //    }
    
        //    if (previousValue != null && previousValue.BillItems.Contains(this))
        //    {
        //        previousValue.BillItems.Remove(this);
        //    }
    
        //    if (MenuItem != null)
        //    {
        //        if (!MenuItem.BillItems.Contains(this))
        //        {
        //            MenuItem.BillItems.Add(this);
        //        }
    
        //        MenuItemId = MenuItem.Id;
        //    }
        //    if (ChangeTracker.ChangeTrackingEnabled)
        //    {
        //        if (ChangeTracker.OriginalValues.ContainsKey("MenuItem")
        //            && (ChangeTracker.OriginalValues["MenuItem"] == MenuItem))
        //        {
        //            ChangeTracker.OriginalValues.Remove("MenuItem");
        //        }
        //        else
        //        {
        //            ChangeTracker.RecordOriginalValue("MenuItem", previousValue);
        //        }
        //        if (MenuItem != null && !MenuItem.ChangeTracker.ChangeTrackingEnabled)
        //        {
        //            MenuItem.StartTracking();
        //        }
        //    }
        //}
    
        //private void FixupUser1(User previousValue, bool skipKeys = false)
        //{
        //    if (IsDeserializing)
        //    {
        //        return;
        //    }
    
        //    if (previousValue != null && previousValue.BillItems1.Contains(this))
        //    {
        //        previousValue.BillItems1.Remove(this);
        //    }
    
        //    if (User1 != null)
        //    {
        //        if (!User1.BillItems1.Contains(this))
        //        {
        //            User1.BillItems1.Add(this);
        //        }
    
        //        ModifiedByUser = User1.Id;
        //    }
        //    else if (!skipKeys)
        //    {
        //        ModifiedByUser = null;
        //    }
    
        //    if (ChangeTracker.ChangeTrackingEnabled)
        //    {
        //        if (ChangeTracker.OriginalValues.ContainsKey("User1")
        //            && (ChangeTracker.OriginalValues["User1"] == User1))
        //        {
        //            ChangeTracker.OriginalValues.Remove("User1");
        //        }
        //        else
        //        {
        //            ChangeTracker.RecordOriginalValue("User1", previousValue);
        //        }
        //        if (User1 != null && !User1.ChangeTracker.ChangeTrackingEnabled)
        //        {
        //            User1.StartTracking();
        //        }
        //    }
        //}

        #endregion
    }
}
