//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace POS.Data.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PriceList))]
    [KnownType(typeof(User))]
    public partial class Check: INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public System.DateTime CreatedTime
        {
            get { return _createdTime; }
            set
            {
                if (_createdTime != value)
                {
                    _createdTime = value;
                    OnPropertyChanged("CreatedTime");
                }
            }
        }
        private System.DateTime _createdTime;
    
        [DataMember]
        public System.Guid CreatedByUserId
        {
            get { return _createdByUserId; }
            set
            {
                if (_createdByUserId != value)
                {
                    _createdByUserId = value;
                    OnPropertyChanged("CreatedByUserId");
                }
            }
        }
        private System.Guid _createdByUserId;
    
        [DataMember]
        public int BillNumber
        {
            get { return _billNumber; }
            set
            {
                if (_billNumber != value)
                {
                    _billNumber = value;
                    OnPropertyChanged("BillNumber");
                }
            }
        }
        private int _billNumber;
    
        [DataMember]
        public System.Guid PriceListId
        {
            get { return _priceListId; }
            set
            {
                if (_priceListId != value)
                {
                    _priceListId = value;
                    OnPropertyChanged("PriceListId");
                }
            }
        }
        private System.Guid _priceListId;
    
        [DataMember]
        public decimal Total
        {
            get { return _total; }
            set
            {
                if (_total != value)
                {
                    _total = value;
                    OnPropertyChanged("Total");
                }
            }
        }
        private decimal _total;
    
        [DataMember]
        public int Guests
        {
            get { return _guests; }
            set
            {
                if (_guests != value)
                {
                    _guests = value;
                    OnPropertyChanged("Guests");
                }
            }
        }
        private int _guests;
    
        [DataMember]
        public bool Printered
        {
            get { return _printered; }
            set
            {
                if (_printered != value)
                {
                    _printered = value;
                    OnPropertyChanged("Printered");
                }
            }
        }
        private bool _printered;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public PriceList PriceList
        {
            get { return _priceList; }
            set
            {
                if (!ReferenceEquals(_priceList, value))
                {
                    _priceList = value;
                    OnNavigationPropertyChanged("PriceList");
                }
            }
        }
        private PriceList _priceList;
    
        [DataMember]
        public User User
        {
            get { return _user; }
            set
            {
                if (!ReferenceEquals(_user, value))
                {
                    _user = value;
                    OnNavigationPropertyChanged("User");
                }
            }
        }
        private User _user;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
    
        #endregion
    }
}
