//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace POS.Data.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Bill))]
    [KnownType(typeof(Check))]
    [KnownType(typeof(Price))]
    public partial class PriceList: INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public ObservableCollection<Bill> Bills
        {
            get
            {
                if (_bills == null)
                {
                    _bills = new ObservableCollection<Bill>();
                }
                return _bills;
            }
            set
            {
                if (!ReferenceEquals(_bills, value))
                {
                    _bills = value;
                    OnNavigationPropertyChanged("Bills");
                }
            }
        }
        private ObservableCollection<Bill> _bills;
    
        [DataMember]
        public ObservableCollection<Check> Checks
        {
            get
            {
                if (_checks == null)
                {
                    _checks = new ObservableCollection<Check>();
                }
                return _checks;
            }
            set
            {
                if (!ReferenceEquals(_checks, value))
                {
                    _checks = value;
                    OnNavigationPropertyChanged("Checks");
                }
            }
        }
        private ObservableCollection<Check> _checks;
    
        [DataMember]
        public ObservableCollection<Price> Prices
        {
            get
            {
                if (_prices == null)
                {
                    _prices = new ObservableCollection<Price>();
                }
                return _prices;
            }
            set
            {
                if (!ReferenceEquals(_prices, value))
                {
                    _prices = value;
                    OnNavigationPropertyChanged("Prices");
                }
            }
        }
        private ObservableCollection<Price> _prices;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;

        #endregion
    }
}
