//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Runtime.Serialization;

namespace POS.Data.Model
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Bill))]
    [KnownType(typeof(BillItem))]
    [KnownType(typeof(Check))]
    [KnownType(typeof(MenuItem))]
    [KnownType(typeof(UserGroup))]
    public partial class User: INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public System.Guid UserGroupId
        {
            get { return _userGroupId; }
            set
            {
                if (_userGroupId != value)
                {
                    _userGroupId = value;
                    OnPropertyChanged("UserGroupId");
                }
            }
        }
        private System.Guid _userGroupId;
    
        [DataMember]
        public Nullable<int> Code
        {
            get { return _code; }
            set
            {
                if (_code != value)
                {
                    _code = value;
                    OnPropertyChanged("Code");
                }
            }
        }
        private Nullable<int> _code;
    
        [DataMember]
        public string Name
        {
            get { return _name; }
            set
            {
                if (_name != value)
                {
                    _name = value;
                    OnPropertyChanged("Name");
                }
            }
        }
        private string _name;
    
        [DataMember]
        public string Card
        {
            get { return _card; }
            set
            {
                if (_card != value)
                {
                    _card = value;
                    OnPropertyChanged("Card");
                }
            }
        }
        private string _card;
    
        [DataMember]
        public bool SexMale
        {
            get { return _sexMale; }
            set
            {
                if (_sexMale != value)
                {
                    _sexMale = value;
                    OnPropertyChanged("SexMale");
                }
            }
        }
        private bool _sexMale;
    
        [DataMember]
        public bool Hidden
        {
            get { return _hidden; }
            set
            {
                if (_hidden != value)
                {
                    _hidden = value;
                    OnPropertyChanged("Hidden");
                }
            }
        }
        private bool _hidden;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public ObservableCollection<Bill> Bills
        {
            get
            {
                if (_bills == null)
                {
                    _bills = new ObservableCollection<Bill>();
                }
                return _bills;
            }
            set
            {
                if (!ReferenceEquals(_bills, value))
                {
                    _bills = value;
                    OnNavigationPropertyChanged("Bills");
                }
            }
        }
        private ObservableCollection<Bill> _bills;
    
        [DataMember]
        public ObservableCollection<BillItem> BillItems
        {
            get
            {
                if (_billItems == null)
                {
                    _billItems = new ObservableCollection<BillItem>();
                }
                return _billItems;
            }
            set
            {
                if (!ReferenceEquals(_billItems, value))
                {
                    _billItems = value;
                    OnNavigationPropertyChanged("BillItems");
                }
            }
        }
        private ObservableCollection<BillItem> _billItems;
    
        [DataMember]
        public ObservableCollection<BillItem> BillItems1
        {
            get
            {
                if (_billItems1 == null)
                {
                    _billItems1 = new ObservableCollection<BillItem>();
                }
                return _billItems1;
            }
            set
            {
                if (!ReferenceEquals(_billItems1, value))
                {
                    _billItems1 = value;
                    OnNavigationPropertyChanged("BillItems1");
                }
            }
        }
        private ObservableCollection<BillItem> _billItems1;
    
        [DataMember]
        public ObservableCollection<Check> Checks
        {
            get
            {
                if (_checks == null)
                {
                    _checks = new ObservableCollection<Check>();
                }
                return _checks;
            }
            set
            {
                if (!ReferenceEquals(_checks, value))
                {
                    _checks = value;
                    OnNavigationPropertyChanged("Checks");
                }
            }
        }
        private ObservableCollection<Check> _checks;
    
        [DataMember]
        public ObservableCollection<MenuItem> MenuItems
        {
            get
            {
                if (_menuItems == null)
                {
                    _menuItems = new ObservableCollection<MenuItem>();
                }
                return _menuItems;
            }
            set
            {
                if (!ReferenceEquals(_menuItems, value))
                {
                    _menuItems = value;
                    OnNavigationPropertyChanged("MenuItems");
                }
            }
        }
        private ObservableCollection<MenuItem> _menuItems;
    
        [DataMember]
        public UserGroup UserGroup
        {
            get { return _userGroup; }
            set
            {
                if (!ReferenceEquals(_userGroup, value))
                {
                    _userGroup = value;
                    OnNavigationPropertyChanged("UserGroup");
                }
            }
        }
        private UserGroup _userGroup;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;

        #endregion
    }
}
